name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy-production:
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
        env:
          ATLAS_URI: ${{secrets.ATLAS_URI}}
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name:  ${{secrets.HEROKU_APP_NAME}}
          heroku_email:  ${{secrets.HEROKU_EMAIL}}
